name: Build CI

on:
  workflow_dispatch:
  push:
    branches-ignore: release
  pull_request:
    types: synchronize
    branches-ignore: release

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  NATIVE_UTILS_LOG_LEVEL: "0"

jobs:

  build-native-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: build
        run: |
          sudo apt update
          sudo apt install -yqq g++-9-arm-linux-gnueabihf \
                                g++-9-aarch64-linux-gnu \
                                g++-9-i686-linux-gnu \
                                musl-tools
          cd ..
          mkdir llvm
          cd llvm
          curl -OL https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-armv7a-linux-gnueabihf.tar.xz
          curl -OL https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-aarch64-linux-gnu.tar.xz
          curl -OL https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-i386-unknown-freebsd12.tar.xz
          tar -xf clang+llvm-12.0.0-armv7a-linux-gnueabihf.tar.xz
          tar -xf clang+llvm-12.0.0-aarch64-linux-gnu.tar.xz
          tar -xf clang+llvm-12.0.0-i386-unknown-freebsd12.tar.xz
          ls -al
          cd ../DFP/
          ls -al
          ./gradlew makeNativeLinux
          ./gradlew makeNativeWrappers
      - uses: actions/upload-artifact@v2
        with:
          name: build-native-linux
          path: |
            ./*native/bin*
            ./*java/dfp/build/generated/sources/nativeWrappers*
            ./*java/dfp-math/build/generated/sources/nativeWrappers*
            ./csharp/EPAM.Deltix.DFP/NativeImpl.cs
            ./csharp/EPAM.Deltix.DFP/Version.targets
            ./csharp/EPAM.Deltix.DFPMath/NativeMathImpl.cs
            ./csharp/EPAM.Deltix.DFPMath/Version.targets
          retention-days: 7

  build-native-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Use MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: build
        run: |
          ./gradlew makeNativeWindows
      - uses: actions/upload-artifact@v2
        with:
          name: build-native-windows
          path: |
            ./*native/bin*
          retention-days: 7

  compress-native:
    runs-on: ubuntu-latest
    needs: [build-native-linux, build-native-windows]
    steps:
      - uses: actions/checkout@v2
      - name: Download native-linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-native-linux
      - name: Download native-windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-native-windows
      - name: Download native-macos artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-native-macos
      - name: compress
        run: |
          zstd --version
          zstd -19 --rm -r ./native/bin
          zstd -19 --rm -r ./native/binmath
      - uses: actions/upload-artifact@v2
        with:
          name: compress-native
          path: |
            ./gradle.properties
            ./*native/bin*
            ./*java/dfp/build/generated/sources/nativeWrappers/com/epam/deltix/dfp*
            ./*java/dfp-math/build/generated/sources/nativeWrappers/com/epam/deltix/dfpmath*
            ./csharp/EPAM.Deltix.DFP/NativeImpl.cs
            ./csharp/EPAM.Deltix.DFP/Version.targets
            ./csharp/EPAM.Deltix.DFPMath/NativeMathImpl.cs
            ./csharp/EPAM.Deltix.DFPMath/Version.targets
          retention-days: 7

  build-java:
    runs-on: ubuntu-latest
    needs: [compress-native]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Download compress-native artifacts
        uses: actions/download-artifact@v2
        with:
          name: compress-native
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: build
        run: |
          ./gradlew jar
          ./gradlew javadocJar
      - uses: actions/upload-artifact@v2
        with:
          name: java-jars
          path: |
            ./*java/dfp/build/libs/*
            ./*java/dfp-math/build/libs/*
            ./*java/decimalDemo/build/libs/*
          retention-days: 7

  test-java:
    runs-on: ${{ matrix.os }}
    needs: [compress-native]
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-2019']
        java: [ '8', '11', '15']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Download compress-native artifacts
        uses: actions/download-artifact@v2
        with:
          name: compress-native
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Show environment
        run: |
          ./gradlew :java:systemInfo:runSystemInfo
      - name: test
        run: |
          ./gradlew check
      - name: Upload test results on failure
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          path: |
            java/dfp/build/reports/*
            java/dfp-math/build/reports/*
          name: Java-{{ matrix.java }}-${{ matrix.os }}-TestReports
